
# [WIP] SHUhelper 后端 API 参考文档
@host = http://localhost:5000
@contentType = application/json
@userID = id
@password = pass
# @name login
POST {{host}}/auth/login
Content-Type: {{contentType}}

{
    "userID": "{{userID}}",
    "password": "{{password}}"
}

###

# @name getTime
GET {{host}}
Authorization: {{login.response.body.token}}

###

# @name index
GET {{host}}
Authorization: {{login.response.body.token}}

###
GET {{host}}/room-booking/rooms
Authorization: {{login.response.body.token}}

###
GET {{host}}/room-booking/orders
Authorization: {{login.response.body.token}}

###
POST {{host}}/lost-n-found/
Content-Type: {{contentType}}
Authorization: {{login.response.body.token}}

{
    "title":"1123",
    "content":"123",
    "category":"123",
    "contact":"18800206081",
    "address":"",
    "type":"found",
    "imgURLs":[],
    "latitude": 12,
    "longitude": 12,
    "occurredTime": 65525
}
###