"""empty message

Revision ID: 19571e4e882b
Revises: 4119146b8fd0
Create Date: 2018-06-16 15:19:38.072401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19571e4e882b'
down_revision = '4119146b8fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('dayoff', sa.Boolean(), nullable=True),
    sa.Column('good', sa.String(), nullable=True),
    sa.Column('bad', sa.String(), nullable=True),
    sa.Column('extra', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar')
    # ### end Alembic commands ###
