"""empty message

Revision ID: 2dcaadda5439
Revises: 53323865a510
Create Date: 2018-04-27 13:13:04.998015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcaadda5439'
down_revision = '53323865a510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cs', sa.String(), nullable=True))
    op.add_column('user', sa.Column('degree', sa.String(), nullable=True))
    op.add_column('user', sa.Column('dept', sa.String(), nullable=True))
    op.add_column('user', sa.Column('education', sa.String(), nullable=True))
    op.add_column('user', sa.Column('intro', sa.String(), nullable=True))
    op.add_column('user', sa.Column('sex', sa.String(), nullable=True))
    op.add_column('user', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'title')
    op.drop_column('user', 'sex')
    op.drop_column('user', 'intro')
    op.drop_column('user', 'education')
    op.drop_column('user', 'dept')
    op.drop_column('user', 'degree')
    op.drop_column('user', 'cs')
    # ### end Alembic commands ###
