"""empty message

Revision ID: 3779f54c23d3
Revises: adfaf2f179df
Create Date: 2018-05-16 15:28:13.647215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3779f54c23d3'
down_revision = 'adfaf2f179df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_n_found_post', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('lost_n_found_post', 'place')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_n_found_post', sa.Column('place', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('lost_n_found_post', 'address')
    # ### end Alembic commands ###
