"""empty message

Revision ID: 39c4c78eaca5
Revises: b0d7d90f5e5f
Create Date: 2018-04-16 22:55:50.734170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39c4c78eaca5'
down_revision = 'b0d7d90f5e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data')
    # ### end Alembic commands ###
