"""empty message

Revision ID: 4119146b8fd0
Revises: ff8ebcff5702
Create Date: 2018-05-30 00:31:14.646810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4119146b8fd0'
down_revision = 'ff8ebcff5702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_class', sa.Column('point', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_class', 'point')
    # ### end Alembic commands ###
