"""empty message

Revision ID: 4894b7cdba97
Revises: 96ca28ceda78
Create Date: 2018-05-29 15:13:58.168720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4894b7cdba97'
down_revision = '96ca28ceda78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_class_campus'), 'class', ['campus'], unique=False)
    op.create_index(op.f('ix_class_capacity'), 'class', ['capacity'], unique=False)
    op.create_index(op.f('ix_class_class_id'), 'class', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_course_id'), 'class', ['course_id'], unique=False)
    op.create_index(op.f('ix_class_credit'), 'class', ['credit'], unique=False)
    op.create_index(op.f('ix_class_teacher_id'), 'class', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_class_term'), 'class', ['term'], unique=False)
    op.create_index(op.f('ix_class_time'), 'class', ['time'], unique=False)
    op.create_index(op.f('ix_course_credit'), 'course', ['credit'], unique=False)
    op.create_index(op.f('ix_course_name'), 'course', ['name'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_course_name'), table_name='course')
    op.drop_index(op.f('ix_course_credit'), table_name='course')
    op.drop_index(op.f('ix_class_time'), table_name='class')
    op.drop_index(op.f('ix_class_term'), table_name='class')
    op.drop_index(op.f('ix_class_teacher_id'), table_name='class')
    op.drop_index(op.f('ix_class_credit'), table_name='class')
    op.drop_index(op.f('ix_class_course_id'), table_name='class')
    op.drop_index(op.f('ix_class_class_id'), table_name='class')
    op.drop_index(op.f('ix_class_capacity'), table_name='class')
    op.drop_index(op.f('ix_class_campus'), table_name='class')
    # ### end Alembic commands ###
