"""empty message

Revision ID: 4bda8c281f13
Revises: d829b48ae320
Create Date: 2018-05-27 16:38:28.215700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bda8c281f13'
down_revision = 'd829b48ae320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('teacher_raw', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'class', ['class_id', 'course_id', 'term'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class', type_='unique')
    op.drop_column('class', 'teacher_raw')
    # ### end Alembic commands ###
