"""empty message

Revision ID: 53323865a510
Revises: 6d3b037d12d6
Create Date: 2018-04-18 11:41:32.295842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53323865a510'
down_revision = '6d3b037d12d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_o_auth', sa.Column('session_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_o_auth', 'session_key')
    # ### end Alembic commands ###
