"""empty message

Revision ID: 53be59f390f8
Revises: d6d219a48798
Create Date: 2018-05-23 21:16:11.364610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53be59f390f8'
down_revision = 'd6d219a48798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('created_at', sa.DateTime()))
    op.add_column('course', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('course', sa.Column('updated_at', sa.DateTime()))
    op.drop_column('course', 'created')
    op.drop_column('course', 'updated')
    op.add_column('lost_n_found_post', sa.Column('created_at', sa.DateTime()))
    op.add_column('lost_n_found_post', sa.Column('location_type', sa.String(), nullable=True))
    op.add_column('lost_n_found_post', sa.Column('updated_at', sa.DateTime()))
    op.drop_column('lost_n_found_post', 'created')
    op.add_column('room', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('room_booking_order', sa.Column('created_at', sa.DateTime()))
    op.add_column('room_booking_order', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('room_booking_order', sa.Column('updated_at', sa.DateTime()))
    op.drop_column('room_booking_order', 'create_time')
    op.add_column('social_o_auth', sa.Column('created_at', sa.DateTime()))
    op.add_column('social_o_auth', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('social_o_auth', sa.Column('updated_at', sa.DateTime()))
    op.drop_column('social_o_auth', 'created_time')
    op.add_column('user', sa.Column('created_at', sa.DateTime()))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime()))
    op.drop_column('user', 'deleted')
    op.drop_column('user', 'creat_time')
    op.add_column('user_data', sa.Column('created_at', sa.DateTime()))
    op.add_column('user_data', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('user_data', sa.Column('updated_at', sa.DateTime()))
    op.add_column('user_data', sa.Column('user_id', sa.String(), nullable=True))
    op.drop_constraint('user_data_user_fkey', 'user_data', type_='foreignkey')
    op.create_foreign_key(None, 'user_data', 'user', ['user_id'], ['id'])
    op.drop_column('user_data', 'created')
    op.drop_column('user_data', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_data', sa.Column('created', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_data', type_='foreignkey')
    op.create_foreign_key('user_data_user_fkey', 'user_data', 'user', ['user'], ['id'])
    op.drop_column('user_data', 'user_id')
    op.drop_column('user_data', 'updated_at')
    op.drop_column('user_data', 'is_deleted')
    op.drop_column('user_data', 'created_at')
    op.add_column('user', sa.Column('creat_time', postgresql.TIMESTAMP(precision=6), autoincrement=False))
    op.add_column('user', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'created_at')
    op.add_column('social_o_auth', sa.Column('created_time', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True))
    op.drop_column('social_o_auth', 'updated_at')
    op.drop_column('social_o_auth', 'is_deleted')
    op.drop_column('social_o_auth', 'created_at')
    op.add_column('room_booking_order', sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('room_booking_order', 'updated_at')
    op.drop_column('room_booking_order', 'is_deleted')
    op.drop_column('room_booking_order', 'created_at')
    op.drop_column('room', 'is_deleted')
    op.add_column('lost_n_found_post', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('lost_n_found_post', 'updated_at')
    op.drop_column('lost_n_found_post', 'location_type')
    op.drop_column('lost_n_found_post', 'created_at')
    op.add_column('course', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False))
    op.add_column('course', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False))
    op.drop_column('course', 'updated_at')
    op.drop_column('course', 'is_deleted')
    op.drop_column('course', 'created_at')
    # ### end Alembic commands ###
