"""empty message

Revision ID: 56fe87ab3bb1
Revises: 4e9f535c371c
Create Date: 2018-05-08 09:17:59.256819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fe87ab3bb1'
down_revision = '4e9f535c371c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_order', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('room_order', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.drop_column('room_order', 'start')
    op.drop_column('room_order', 'end')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_order', sa.Column('end', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('room_order', sa.Column('start', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('room_order', 'start_time')
    op.drop_column('room_order', 'end_time')
    # ### end Alembic commands ###
