"""empty message

Revision ID: 66e2bf2f0df4
Revises: 2dcaadda5439
Create Date: 2018-04-30 20:00:41.186279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66e2bf2f0df4'
down_revision = '2dcaadda5439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_n_found_post',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('img_URLs', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('occurred_time', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('is_found', sa.Boolean(), nullable=True),
    sa.Column('hit', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('lighten_time', sa.DateTime(), nullable=True),
    sa.Column('lighten_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('teacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('open_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('creat_time', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('activated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('robot', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pw_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatar_URL', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cs', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('degree', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dept', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('education', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('intro', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('css', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.drop_table('lost_n_found_post')
    # ### end Alembic commands ###
