"""empty message

Revision ID: 6fe1f6d10332
Revises: 53be59f390f8
Create Date: 2018-05-24 14:59:21.747175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6fe1f6d10332'
down_revision = '53be59f390f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_members',
    sa.Column('order_id', postgresql.UUID(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['room_booking_order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_members')
    # ### end Alembic commands ###
