"""empty message

Revision ID: 903f6d8fe641
Revises: 5aa9c7babb7c
Create Date: 2018-05-22 11:41:11.380430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903f6d8fe641'
down_revision = '5aa9c7babb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
