"""empty message

Revision ID: 99e30d168b9a
Revises: 6fe1f6d10332
Create Date: 2018-05-26 18:26:51.970105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99e30d168b9a'
down_revision = '6fe1f6d10332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_class',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('enroll', sa.Integer(), nullable=True),
    sa.Column('campus', sa.String(), nullable=True),
    sa.Column('q_time', sa.String(), nullable=True),
    sa.Column('q_place', sa.String(), nullable=True),
    sa.Column('credit', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_class',
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('class_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('grade_1', sa.Integer(), nullable=True),
    sa.Column('grade_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['t_class.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['undergraduate_student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'class_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_class')
    op.drop_table('t_class')
    # ### end Alembic commands ###
