"""empty message

Revision ID: adfaf2f179df
Revises: e451e29ce55a
Create Date: 2018-05-12 13:07:10.484311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfaf2f179df'
down_revision = 'e451e29ce55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_booking_order', sa.Column('contact', sa.String(), nullable=True))
    op.add_column('room_booking_order', sa.Column('teacher', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_booking_order', 'teacher')
    op.drop_column('room_booking_order', 'contact')
    # ### end Alembic commands ###
