"""empty message

Revision ID: b0d7d90f5e5f
Revises: e2867411f913
Create Date: 2018-04-11 11:09:40.475566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d7d90f5e5f'
down_revision = 'e2867411f913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_o_auth', sa.Column('created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_o_auth', 'created_time')
    # ### end Alembic commands ###
