"""empty message

Revision ID: d6d219a48798
Revises: 903f6d8fe641
Create Date: 2018-05-23 09:24:23.497050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d219a48798'
down_revision = '903f6d8fe641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('dept', sa.String(), nullable=True))
    # op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('course', 'dept')
    # ### end Alembic commands ###
