"""empty message

Revision ID: d829b48ae320
Revises: c4d498becade
Create Date: 2018-05-27 16:02:33.181216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd829b48ae320'
down_revision = 'c4d498becade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('classroom', sa.String(), nullable=True))
    op.drop_column('class', 'place')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('place', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('class', 'classroom')
    # ### end Alembic commands ###
