"""empty message

Revision ID: dca22f874919
Revises: 2525683b79b9
Create Date: 2018-04-11 10:15:56.444913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca22f874919'
down_revision = '2525683b79b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('building', sa.String(), nullable=True))
    op.add_column('room', sa.Column('campus', sa.String(), nullable=True))
    op.add_column('room', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('floor', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('group', sa.String(), nullable=True))
    op.add_column('room', sa.Column('no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'no')
    op.drop_column('room', 'group')
    op.drop_column('room', 'floor')
    op.drop_column('room', 'capacity')
    op.drop_column('room', 'campus')
    op.drop_column('room', 'building')
    # ### end Alembic commands ###
