"""empty message

Revision ID: e451e29ce55a
Revises: ebe4c315fd96
Create Date: 2018-05-09 10:17:02.947830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e451e29ce55a'
down_revision = 'ebe4c315fd96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_booking_order', sa.Column('end', sa.Integer(), nullable=True))
    op.add_column('room_booking_order', sa.Column('start', sa.Integer(), nullable=True))
    op.drop_column('room_booking_order', 'end_time')
    op.drop_column('room_booking_order', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_booking_order', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('room_booking_order', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('room_booking_order', 'start')
    op.drop_column('room_booking_order', 'end')
    # ### end Alembic commands ###
