"""empty message

Revision ID: ebe4c315fd96
Revises: ece6184b2e6d
Create Date: 2018-05-08 13:36:08.507060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe4c315fd96'
down_revision = 'ece6184b2e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('building', sa.String(), nullable=True))
    op.add_column('room', sa.Column('campus', sa.String(), nullable=True))
    op.add_column('room', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('floor', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('group', sa.String(), nullable=True))
    op.add_column('room', sa.Column('no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'no')
    op.drop_column('room', 'group')
    op.drop_column('room', 'floor')
    op.drop_column('room', 'capacity')
    op.drop_column('room', 'campus')
    op.drop_column('room', 'building')
    # ### end Alembic commands ###
