"""empty message

Revision ID: f0e7e6e9f4c2
Revises: 3779f54c23d3
Create Date: 2018-05-18 11:52:54.790266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e7e6e9f4c2'
down_revision = '3779f54c23d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_n_found_post', sa.Column('site', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lost_n_found_post', 'site')
    # ### end Alembic commands ###
