"""empty message

Revision ID: ff8ebcff5702
Revises: 4894b7cdba97
Create Date: 2018-05-29 20:29:33.773811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8ebcff5702'
down_revision = '4894b7cdba97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_class', sa.Column('grade', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_class', 'grade')
    # ### end Alembic commands ###
