"""second migration

Revision ID: a067bd87ea63
Revises: d5029b8b9306
Create Date: 2017-02-20 19:07:17.988115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a067bd87ea63'
down_revision = 'd5029b8b9306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courseno', sa.String(length=30), nullable=True),
    sa.Column('coursename', sa.String(length=30), nullable=True),
    sa.Column('teachno', sa.String(length=30), nullable=True),
    sa.Column('teachename', sa.String(length=30), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('time', sa.String(length=30), nullable=True),
    sa.Column('place', sa.String(length=30), nullable=True),
    sa.Column('delay', sa.String(length=30), nullable=True),
    sa.Column('note', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    # ### end Alembic commands ###
