"""empty message

Revision ID: d5029b8b9306
Revises: 69e6154ca2ab
Create Date: 2017-01-04 23:50:14.133761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5029b8b9306'
down_revision = '69e6154ca2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('students_id', sa.String(length=200), nullable=True),
    sa.Column('login_site', sa.String(length=200), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
